### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by KennethTrecy** [KennethTrecy/peratorakka_server#1]
# Road Map
To build the system carefully, the road map has been created with different phases.

1. Initial Setup
   - [x] Make registration route
   - [x] Make log in route
   - [x] Setup tests
   - [x] Make necessary guards to prevent manipulation of unowned records
   - [x] Integrate libraries to handle authentication
2. Account Availability
   - [x] Make CRUD routes for currencies
   - [x] Make CRUD routes for accounts
3. Financial Entry Availability
   - [x] Make CRUD routes for modifiers invoked by manual input
   - [x] Make CRUD routes for financial entry caused by modifiers
4. Frozen Periods Availability
   - [x] Make CRUD routes for frozen periods
5. Collections Availability
   - [x] Make CRUD routes for collections
   - [x] Make view routes to get aggregated info from collection
6. Formula Availability
   - [x] Make CRUD routes for formula
   - [x] Integrate the aggregation of formula to collections
7. Reactive Modifiers Availability
   - [ ] Make CRUD routes for events triggered manually
   - [ ] Upgrade routes for modifiers to react on events
   - [ ] Make route to trigger a manual event
8. Dependent Modifiers Availability
   - [ ] Upgrade routes for modifiers to depend on other modifiers
9. Timed Events Availability
   - [ ] Upgrade routes for events to handle interval events
   - [ ] Upgrade routes for events to handle timeout events
   - [ ] Conceive a way to handle missed schedules

**Comment by KennethTrecy** [comment]
The road has been changed due to new priorities.
Specialized modifiers may be deferred until more realizations come up.
